package com.example.mojo.helloglass;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.speech.tts.TextToSpeech;
import android.util.Log;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;

import com.example.mojo.helloglass.adapter.MovieCardsAdapter;
import com.example.mojo.helloglass.bluetooth.BluetoothActivity;
import com.example.mojo.helloglass.model.MovieCard;
import com.google.android.glass.app.Card;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollView;
import com.google.glass.companion.CompanionMessagingUtil;
import com.google.glass.companion.Proto;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;


/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p/>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 *
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */
public class MainActivity extends Activity implements
        TextToSpeech.OnInitListener {

    /**
     * {@link CardScrollView} to use as the main content view.
     */
    //private CardScrollView mCardScroller;



    /**
     * "Hello World!" {@link View} generated by {@link #buildView()}.
     */
    //private View mView;

    private List<MovieCard> mCards;
    private CardScrollView mCardScrollView;
    private Context context;
    private TextToSpeech tts;

    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);

        //mView = buildView();
        //mCardScroller = new CardScrollView(this);

        //This is the movie cards implementation
        context = this;
        prepareMovieCards();

        mCardScrollView =  new CardScrollView(this);
        MovieCardsAdapter adapter = new MovieCardsAdapter(context, mCards);
        mCardScrollView.setAdapter(adapter);
        mCardScrollView.activate();


        //Text to speech initialization
        tts = new TextToSpeech(this, this);


//        mCardScroller.setAdapter(new CardScrollAdapter() {
//            @Override
//            public int getCount() {
//                return 1;
//            }
//
//            @Override
//            public Object getItem(int position) {
//                return mView;
//            }
//
//            @Override
//            public View getView(int position, View convertView, ViewGroup parent) {
//                return mView;
//            }
//
//            @Override
//            public int getPosition(Object item) {
//                if (mView.equals(item)) {
//                    return 0;
//                }
//                return AdapterView.INVALID_POSITION;
//            }
//        });
        //Handle the TAP event.
        mCardScrollView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                openOptionsMenu();
//                Intent ia = new Intent(MainActivity.this, MenuActivity.class);
//                startActivity(ia);

            }
        });
        //setContentView(mCardScroller);
        setContentView(mCardScrollView);

    }

    private void prepareMovieCards() {
        mCards = new ArrayList<MovieCard>();

        // Card with full background image
        MovieCard mc = new MovieCard("I wanna go home. Does anyone know where my dad is?",
                "Pet store?", Card.ImageLayout.FULL,
                new int[] { R.drawable.card_full });
        mCards.add(mc);
        // Card with no background image
        mc = new MovieCard("I don't know. But who cares! Ha ha!",
                "Wait! What does that mean?", Card.ImageLayout.FULL, new int[] {});
        mCards.add(mc);


        // Card with full background of 3 images
        mc = new MovieCard("Dude? Dude? Focus dude... Dude?",
                "Oh, he lives. Hey, dude!", Card.ImageLayout.FULL, new int[] {
                R.drawable.card_bottom_left,
                R.drawable.card_bottom_right, R.drawable.card_top });
        mCards.add(mc);

        // Card with left aligned images
        mc = new MovieCard("Just keep swimming.",
                "I'm sorry, Dory. But I... do", Card.ImageLayout.LEFT, new int[] {
                R.drawable.card_bottom_left,
                R.drawable.card_bottom_right, R.drawable.card_top });
        mCards.add(mc);

    }


//    @Override
//    protected void onCreate(Bundle savedInstanceState) {
//        super.onCreate(savedInstanceState);
//        setContentView(R.menu.main);
//    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {

        switch (item.getItemId()) {
            case R.id.action_about:
                // About menu item selected
                Intent ia = new Intent(MainActivity.this, AboutActivity.class);
                startActivity(ia);
                Intent intnet = new Intent("com.hmkcode.android.USER_ACTION");
                sendBroadcast(intnet);
                return true;
            case R.id.action_live:
                // this is the service to create a live card
                startService(new Intent(this, LiveCardService.class));
                return true;
            case R.id.action_poke_phone:
                // this is the service to create a live card
                /*try {
                    pokePhone();
                } catch (Exception e) {
                    e.printStackTrace();
                }*/
                Intent intent = new Intent(this, BluetoothActivity.class);
                this.startActivity(intent);
            case R.id.action_speak:
//                Plays disallowed sound to indicate that TAP actions are not supported.
//                AudioManager am = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
//                am.playSoundEffect(Sounds.DISALLOWED);
                speakOut();
                return true;
            case R.id.action_quit:
                // Quit menu item selected
                // we'll simply close the app
                LiveCardService liveCardService = new LiveCardService();
                liveCardService.mLiveCard.unpublish();
                liveCardService.stopSelf();
                finish();
                this.finishAffinity();
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    private void pokePhone() throws Exception {
        Proto.Envelope envelope = CompanionMessagingUtil.newEnvelope();
        envelope.serialNumber = 12408317;
        JoeMessageUtil.send(envelope);
    }

    @Override
    public void onInit(int status) {

        if (status == TextToSpeech.SUCCESS) {

            int result = tts.setLanguage(Locale.US);

            if (result == TextToSpeech.LANG_MISSING_DATA
                    || result == TextToSpeech.LANG_NOT_SUPPORTED) {
                Log.e("TTS", "This Language is not supported");
            } else {

            }

        } else {
            Log.e("TTS", "Initilization Failed!");
        }

    }

    private void speakOut() {

        //String text = txtText.getText().toString();

        tts.speak("Hello Bhonda", TextToSpeech.QUEUE_FLUSH, null);
    }

    @Override
    public void openOptionsMenu() {
        super.openOptionsMenu();

    }


    @Override
    protected void onResume() {
        super.onResume();
        //mCardScroller.activate();
        mCardScrollView.activate();
    }

    @Override
    protected void onPause() {
        //mCardScroller.deactivate();
        mCardScrollView.deactivate();
        super.onPause();
    }

    /**
     * Builds a Glass styled "Hello World!" view using the {@link CardBuilder} class.
     */
    private View buildView() {
        CardBuilder card = new CardBuilder(this, CardBuilder.Layout.TEXT);
        card.setText("Tap for options");
        return card.getView();
    }

    @Override
    public void onDestroy() {
        // Don't forget to shutdown tts!
        if (tts != null) {
            tts.stop();
            tts.shutdown();
        }
        super.onDestroy();
    }

}
